services:
  pillar-api-v1:
    build:
      context: ../
      dockerfile: docker/api-dockerfile
    env_file:
      - path: ../.env
        required: true
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ../src:/app/src

  mysql:
    image: mysql:9.1
    env_file:
      - path: ../.env
        required: true
    environment:
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
      MYSQL_DATABASE: $(MYSQL_DATABASE)
      MYSQL_USER: $(MYSQL_USER)
      MYSQL_PASSWORD: $(MYSQL_PASSWORD)
    ports:
      - "3306:3306"
